suppressPackageStartupMessages({library(here);library(png);library(grid);library(gridExtra)})
int<-here("results","figures","intermediate","figure3");main<-here("results","figures","main");dir.create(main,recursive=TRUE,showWarnings=FALSE)
a<-rasterGrob(readPNG(file.path(int,"Figure3A_overall_Braak_waterfall.png")),interpolate=TRUE)
b<-rasterGrob(readPNG(file.path(int,"Figure3B_Braak_forest.png")),interpolate=TRUE)
panel<-function(label,img) arrangeGrob(textGrob(label,x=0,just="left",gp=gpar(fontsize=16,fontface="bold")),img,ncol=1,heights=c(.35,7))
fig<-arrangeGrob(panel("(A)",a),panel("(B)",b),ncol=2)
png(file.path(main,"Figure3_Braak_overall.png"),4800,2400,res=300);grid.draw(fig);dev.off()
pdf(file.path(main,"Figure3_Braak_overall.pdf"),16,8,useDingbats=FALSE);grid.draw(fig);dev.off()
message("Saved reproducible Figure 3.")
